public enum MoveCondition {
    NONE, BURN, PARALYSIS, POISON, SLEEP, FREEZE,
    CONFUSION, FLINCH, LEECH_SEED,
    STAT_ATTACK_UP, STAT_ATTACK_DOWN,
    STAT_DEFENSE_UP, STAT_DEFENSE_DOWN,
    STAT_SPEED_UP, STAT_SPEED_DOWN,
    STAT_ACCURACY_UP, STAT_ACCURACY_DOWN,
    STAT_EVASION_UP, STAT_EVASION_DOWN,
    RECOIL, HEAL
}